# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac26b2be82ae50aab8f6e59966bff1627470f79e9fdaa3ffb06197395b91cf5b3d34bab29ffbd2d4d80156ba8e377f4a16df00fb9039766f5f739c0cf6f5fda8

test:
  secret_key_base: 1ab1dbb7e3848c57222fa19661a5b874195353516efd7e05d2b6de8644f58325535a6a744be4dc23154ffedd9cc25868ab06f7a98db395351c382a3b9a0486a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
